// ============================================================
//  main.cpp  --  Centralized Blood Bank & Donor Management System
//  Author  : Esha Qaisar (Team Lead)  |  Roll: 25L-2009
//  Team 12 | BSCY-2A | Semester 2
//
//  RESPONSIBILITY (per Master Execution Plan - Domain 4):
//    - Application entry point
//    - Application-wide routing:
//        LandingPage -> LoginForm -> [Admin/Donor/Patient] Dashboard
//    - Background transaction logger initialisation
//    - File structure verification on startup
//
//  HOW TO BUILD (Visual Studio 2019/2022):
//    1.  New Project -> C++/CLR -> Windows Forms App
//    2.  Copy this file + all .h/.cpp from Models/, UI_Forms/,
//        Utilities/ into the project.
//    3.  Set main.cpp as the startup file.
//    4.  Build -> Run  (x86 or x64, Debug or Release)
//
//  DO NOT EDIT this file unless you are Esha Qaisar.
// ============================================================

#pragma comment(lib, "user32.lib")     // required for SendMessage in style.cpp

// --- CLR / WinForms headers ---
#include <windows.h>

#using <System.dll>
#using <System.Drawing.dll>
#using <System.Windows.Forms.dll>

// --- Project headers (Esha's domain) ---
#include "Utilities/style.h"
#include "UI_Forms/LandingPage.h"
#include "Utilities/FileManager.h"

using namespace System;
using namespace System::Windows::Forms;

// ============================================================
//  Forward declarations (other team members' screens)
//  These are defined in their respective .h files.
//  Do NOT change these -- just add a new line if a new screen
//  is created.
// ============================================================
//  Esha   : LandingPage, LoginForm, SignupForm, AdminDashboard
//  Ali    : DonorDashboard, DonorRegistrationForm, DonorListForm
//  Zara   : InventoryDashboard
//  Noor   : PatientDashboard, BloodRequestForm, RequestManagementForm

// ============================================================
//  APPLICATION ENTRY POINT
// ============================================================
[STAThread]
int main(array<System::String^>^ args)
{
    // --- WinForms bootstrap ---
    Application::EnableVisualStyles();
    Application::SetCompatibleTextRenderingDefault(false);

    try
    {
        // --- Verify / create database folder and text files ---
        FileManager::InitialiseStorage();

        // --- Log application start ---
        FileManager::LogTransaction("SYSTEM", "Application started.");

        // --- Launch the Landing Page (first screen the user sees) ---
        // LandingPage shows two buttons:
        //   "Login as Admin"  ->  LoginForm (role = Admin)
        //   "Login as User"   ->  LoginForm (role = User/Donor/Patient)
        Application::Run(gcnew LandingPage());

        // --- Log clean exit ---
        FileManager::LogTransaction("SYSTEM", "Application exited normally.");
    }
    catch (Exception^ ex)
    {
        // --- Catch any fatal application crashes and log them ---
        FileManager::LogTransaction("FATAL_ERROR", "Application crashed: " + ex->Message);

        // Show a professional error to the user before closing
        MessageBox::Show(
            "A critical error occurred. Please check the system logs for details.\n\nError: " + ex->Message,
            "System Error",
            MessageBoxButtons::OK,
            MessageBoxIcon::Error
        );
    }

    return 0;
}